/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as KioskLoginRouteImport } from './routes/kiosk-login'
import { Route as KioskRouteImport } from './routes/kiosk'

const KioskLoginRoute = KioskLoginRouteImport.update({
  id: '/kiosk-login',
  path: '/kiosk-login',
  getParentRoute: () => rootRouteImport,
} as any)
const KioskRoute = KioskRouteImport.update({
  id: '/kiosk',
  path: '/kiosk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/kiosk': typeof KioskRoute
  '/kiosk-login': typeof KioskLoginRoute
}
export interface FileRoutesByTo {
  '/kiosk': typeof KioskRoute
  '/kiosk-login': typeof KioskLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/kiosk': typeof KioskRoute
  '/kiosk-login': typeof KioskLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/kiosk' | '/kiosk-login'
  fileRoutesByTo: FileRoutesByTo
  to: '/kiosk' | '/kiosk-login'
  id: '__root__' | '/kiosk' | '/kiosk-login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  KioskRoute: typeof KioskRoute
  KioskLoginRoute: typeof KioskLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/kiosk-login': {
      id: '/kiosk-login'
      path: '/kiosk-login'
      fullPath: '/kiosk-login'
      preLoaderRoute: typeof KioskLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kiosk': {
      id: '/kiosk'
      path: '/kiosk'
      fullPath: '/kiosk'
      preLoaderRoute: typeof KioskRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  KioskRoute: KioskRoute,
  KioskLoginRoute: KioskLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
